require "lua/tools"

local res = io.popen("mkdir " .. tmpdir)
print("mkdir " .. tmpdir, res:read("*a"))
res.close()

header("Main program")
print("Hello, world!")
header()
LuaLept:DebugOn("udata", "array")
print(pad("LuaLept:Debug()"), LuaLept:Debug())
print(pad("LuaLept:Version()"), LuaLept:Version())
print(pad("LuaLept:LuaVersion()"), LuaLept:LuaVersion())
print(pad("LuaLept:LeptVersion()"), LuaLept:LeptVersion())

-- bmf_test()
-- aset_test()
-- amap_test()
-- pta_test()
-- box_test()
-- numa_test()
-- dna_test()
-- pix_test()
-- pix_test2()
-- fpix_test()
-- dpix_test()
-- pix_test3()

header()
print("That's all, folks!")
